version: '3.4'

services:
  api:
    build: /api/Ship.CRUD
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7244:80

  client:
    build: /client/ship-crud
    container_name: client
    ports:
      - 4200:80
    links:
      - api
